//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public string ExpenseItem { get; set; }
        public string ExpenseCost { get; set; }
    }
}
